version: '3'

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'

  production:
    build:
      context: .
      dockerfile: Dockerfile.
    ports:
      - '8001:8001'
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failuer
        max_attempts: 3
        delay: 10s
        window: 180s
